use_frameworks!

target 'CoreTesting_Example' do
  pod 'SnapKit'

  target 'CoreTesting_Tests' do
    inherit! :search_paths

    pod 'SnapshotTesting', '~> 1.7.2'
    pod 'LayoutTest/Swift', '~> 6.0.1'
    pod 'CoreTesting', :path => '../'
    
  end
end
